path: /home/janik/projects/master/graphnet/data/examples/output/convert_parquet_to_sqlite/merge503_graph_net/data/merge503_graph_net.db
pulsemaps:
  - detector_response
features:
  - pmt_x
  - pmt_y
  - pmt_z
  - pmt_azimuth
  - pmt_zenith
  - time
truth:
  - energy
  - interaction_x
  - interaction_y
  - interaction_z
  - azimuth
  - zenith
  - pid
  - interaction_type
index_column: event_no
truth_table: mc_truth
seed: 21
selection:
  test: 10 random events ~ event_no % 5 == 0
  #  test_hit: 10 random events ~ event_no % 5 == 0 & abs(pid) == 11
  #  test_noise: 10 random events ~ event_no % 5 == 0 & abs(pid) == 1

  validation_hit: 2 random events ~ event_no % 5 == 1 & abs(pid) == 11
  validation_noise: 2 random events ~ event_no % 5 == 1 & abs(pid) == 1

  train_hit: 5 random events ~ event_no % 5 > 1 & abs(pid) == 11
  train_noise: 5 random events ~ event_no % 5 > 1 & abs(pid) == 1
